name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
  push:
    branches: [main, develop]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          python-version: "3.7.3"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install matplotlib
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          python unit_test.py -v
